spring.application.name=AUTH-SERVICE
server.port=8081

eureka.client.service-url.defaultZone=https://hospital-microservices-4xcu.onrender.com/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true